local_backend: true
backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: 'src/content/assets' # Media files will be stored in the repo under static/images/uploads
public_folder: '../assets' # The src attribute for uploaded media will begin with /images/uploads
collections:
  - name: 'galeries'
    label: 'Galeries'
    folder: 'src/content/galeries'
    create: true
    slug: '{{slug}}-}-{{day}}-{{month}}-{{year}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Date de publication', name: 'date', widget: 'datetime' }
      - label: 'Images'
        name: 'images'
        minimize_collapsed: true
        widget: 'list'
        summary: '{{fields.image}}'
        add_to_top: true
        fields:
          - { label: 'image', name: 'image', widget: 'image' }
          - { label: titre, name: title, widget: string, required: false }
  - name: 'articles' # Used in routes, e.g., /admin/collections/blog
    label: 'Articles' # Used in the UI
    folder: 'src/content/articles' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '{{slug}}-{{day}}-{{month}}-{{year}}' # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Date de publication', name: 'date', widget: 'datetime' }
      - {
          label: 'Catégorie',
          name: 'category',
          widget: 'select',
          options: ['6eme', '5eme', '4eme', '3eme']
        }
      - { label: 'Image de couverture', name: 'image', widget: 'image' }
      - { label: 'Description', name: 'altImage', widget: 'text', required: false }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - label: 'Références'
        name: 'references'
        minimize_collapsed: true
        widget: 'list'
        summary: '{{fields.image}}'
        fields:
          - { label: 'image', name: 'image', widget: 'image' }
          - { label: titre, name: title, widget: string, required: false }
          - { label: Auteur, name: author, widget: string, required: false }
          - { label: Autre, name: other, widget: string, required: false }
